import = ["~/.config/alacritty/themes/themes/nord.toml"]
[font]
size = 13.0
normal = { family = "JetBrains Mono ", style = "Regular" }
bold = { family = "JetBrains Mono ", style = "Bold" }
italic = { family = "JetBrains Mono ", style = "Italic" }
bold_italic = { family = "JetBrains Mono ", style = "Bold  Italic" }

# [selection]
# save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true


#cursor
[cursor]
style = { blinking = "On" }

#keyboard
[keyboard]
bindings = [
  { key = "H", mods = "Control|Shift", action = "SearchFocusNext" },
  { key = "L", mods = "Control|Shift", action = "SearchFocusPrevious" },
  { key = "V", mods = "Control|Alt", action = "ToggleViMode" },
]
